/*
  WeatherLocationCard.spec.ts

  Purpose:
  Contains unit/component tests for the WeatherLocationCard component.
  These tests verify that weather information is displayed correctly,
  that each card links to the correct weather detail route, and that
  the appropriate OpenWeather icon is displayed.
*/

import { describe, expect, it } from 'vitest'
import { mount } from '@vue/test-utils'
import { createMemoryHistory, createRouter } from 'vue-router'

import WeatherLocationCard from '@/components/molecules/WeatherLocationCard.vue'

// Provides sample weather data used throughout the tests.
// Milan is used as a predictable test location.
const testLocation = {
  id: 123,
  city: 'Milan',
  subtitle: 'Lombardy, IT',
  temperature: 25,
  high: 28,
  low: 19,
  description: 'clear sky',
  weatherIcon: '01d',
  backgroundImage: '',
  lat: 45.4642,
  lon: 9.19,
}

// Creates a temporary Vue Router specifically for testing.
// Memory history is used so the tests do not depend on
// the browser's actual navigation history.
function createTestRouter() {
  return createRouter({
    history: createMemoryHistory(),

    routes: [
      {
        // Provides a simple test version of the home route.
        path: '/',
        name: 'home',
        component: {
          template: '<div>Home</div>',
        },
      },
      {
        // Provides the dynamic weather detail route used
        // when a weather location card is selected.
        path: '/weather/:lat/:lon',
        name: 'weather-detail',
        component: {
          template: '<div>Weather Detail</div>',
        },
      },
    ],
  })
}

// Groups all tests related to WeatherLocationCard.
describe('WeatherLocationCard', () => {
  // Checks that the weather card correctly displays
  // the information supplied through its location prop.
  it('displays the location weather information', async () => {
    const router = createTestRouter()

    // Starts the test router on the home page.
    await router.push('/')
    await router.isReady()

    // Mounts the WeatherLocationCard using the sample Milan data.
    const wrapper = mount(WeatherLocationCard, {
      props: {
        location: testLocation,
      },

      // Installs the test router because the component
      // contains a RouterLink.
      global: {
        plugins: [router],
      },
    })

    // Confirms that the expected weather information
    // appears somewhere within the rendered card.
    expect(wrapper.text()).toContain('Milan')
    expect(wrapper.text()).toContain('25°')
    expect(wrapper.text()).toContain('clear sky')
    expect(wrapper.text()).toContain('H:28°')
    expect(wrapper.text()).toContain('L:19°')
  })

  // Checks that clicking/navigation through the card
  // would lead to the correct weather detail URL.
  it('links to the correct weather detail page', async () => {
    const router = createTestRouter()

    await router.push('/')
    await router.isReady()

    const wrapper = mount(WeatherLocationCard, {
      props: {
        location: testLocation,
      },

      global: {
        plugins: [router],
      },
    })

    // Gets the anchor element generated by RouterLink.
    const link = wrapper.get('a')

    // Confirms that the latitude and longitude from the location
    // are correctly included in the dynamic route.
    expect(link.attributes('href')).toBe('/weather/45.4642/9.19')
  })

  // Checks that the card displays the correct OpenWeather icon
  // and provides the weather description as alternative text.
  it('displays the correct weather icon', async () => {
    const router = createTestRouter()

    await router.push('/')
    await router.isReady()

    const wrapper = mount(WeatherLocationCard, {
      props: {
        location: testLocation,
      },

      global: {
        plugins: [router],
      },
    })

    // Finds the weather icon rendered by the component.
    const image = wrapper.get('.weather-card__icon')

    // Confirms that the OpenWeather icon code is converted
    // into the expected image URL.
    expect(image.attributes('src')).toBe('https://openweathermap.org/img/wn/01d@4x.png')

    // Confirms that the weather description is used
    // as accessible alternative text for the image.
    expect(image.attributes('alt')).toBe('clear sky')
  })
})
